/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    works: Work;
    services: Service;
    'manifesto-statements': ManifestoStatement;
    pages: Page;
    cities: City;
    businesses: Business;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    works: WorksSelect<false> | WorksSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'manifesto-statements': ManifestoStatementsSelect<false> | ManifestoStatementsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    businesses: BusinessesSelect<false> | BusinessesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'id') | ('en' | 'id')[];
  globals: {
    'site-settings': SiteSetting;
    'hero-effects': HeroEffect;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'hero-effects': HeroEffectsSelect<false> | HeroEffectsSelect<true>;
  };
  locale: 'en' | 'id';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works".
 */
export interface Work {
  id: number;
  title: string;
  slug: string;
  category: 'brand' | 'web' | 'motion' | 'engineering';
  year: number;
  /**
   * One-sentence description — shown as "// 01 Description" in the homepage works carousel
   */
  oneLiner?: string | null;
  /**
   * Comma-separated services list — "// 02 Services" in the works carousel (e.g. "Art Direction, Motion Graphics")
   */
  servicesLine?: string | null;
  /**
   * "// 03 Industry" in the works carousel
   */
  industry?: string | null;
  /**
   * "// 04 Location" in the works carousel
   */
  location?: string | null;
  cover?: (number | null) | Media;
  featured?: boolean | null;
  /**
   * Position on the drag-canvas archive (canvas units)
   */
  archiveSlot?: {
    x?: number | null;
    y?: number | null;
    scale?: number | null;
  };
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  /**
   * Bold headline inside the expanded row (e.g. "Shaping identities that resonate and endure")
   */
  tagline?: string | null;
  /**
   * Paragraph inside the expanded row
   */
  description?: string | null;
  capabilities?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown as "003//" on the row (manual for now — works aren’t related to services yet)
   */
  projectCount?: number | null;
  /**
   * Stroke icon shown next to the service name
   */
  icon?: ('strategy' | 'grid' | 'motion' | 'code' | 'pen' | 'layers' | 'camera' | 'spark') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manifesto-statements".
 */
export interface ManifestoStatement {
  id: number;
  text: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout?:
    | (
        | {
            line1: string;
            line2?: string | null;
            locationLine?: string | null;
            scrollCue?: string | null;
            /**
             * Planets orbiting the logo — one per approved business (Semesta → Businesses). Turning this off leaves the logo alone in the hero; nothing else breaks.
             */
            orbitEnabled?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'manifestoStrip';
          }
        | {
            heading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredWorks';
          }
        | {
            heading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'servicesRows';
          }
        | {
            countTemplate?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'archiveTeaser';
          }
        | {
            heading?: string | null;
            emailOverride?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactMailto';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            media?: (number | null) | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaFull';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  name: string;
  /**
   * Province or country — shown after the city on a planet label
   */
  region?: string | null;
  /**
   * Decimal degrees, north positive (Surakarta = -7.5665)
   */
  lat: number;
  /**
   * Decimal degrees, east positive (Surakarta = 110.8167)
   */
  lng: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Each approved row is one planet orbiting the hero logo. Filter by status = pending to work the approval queue.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businesses".
 */
export interface Business {
  id: number;
  /**
   * Shown on hover. 60 characters is a name, not a sentence.
   */
  name: string;
  city: number | City;
  /**
   * Decides the planet’s base shape, so two planets never read alike.
   */
  kind: 'clinic' | 'food' | 'craft' | 'retail' | 'service' | 'education' | 'other';
  /**
   * Optional. Rendered rel="nofollow ugc" — this is the field spam submissions come for.
   */
  website?: string | null;
  /**
   * Sets how close the planet orbits: the older the business, the tighter its orbit.
   */
  foundedYear?: number | null;
  /**
   * How the planet is drawn. The submitter picks these.
   */
  planet?: {
    size?: ('small' | 'medium' | 'large') | null;
    pattern?: ('plain' | 'crosshatch' | 'stipple' | 'ringed') | null;
    ink?: ('graphite' | 'red' | 'sepia' | 'blue') | null;
  };
  /**
   * The mark the planet leaves behind it.
   */
  trail?: {
    style?: ('line' | 'dots' | 'ticks' | 'none') | null;
    length?: ('short' | 'medium' | 'long') | null;
  };
  /**
   * Leave empty and the plane is derived from the name — stable, and spread evenly.
   */
  orbit?: ('a' | 'b' | 'c') | null;
  status: 'pending' | 'approved' | 'rejected';
  /**
   * Admin-only. Never exposed to the public API.
   */
  contactEmail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'works';
        value: number | Work;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'manifesto-statements';
        value: number | ManifestoStatement;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'businesses';
        value: number | Business;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works_select".
 */
export interface WorksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  year?: T;
  oneLiner?: T;
  servicesLine?: T;
  industry?: T;
  location?: T;
  cover?: T;
  featured?: T;
  archiveSlot?:
    | T
    | {
        x?: T;
        y?: T;
        scale?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  description?: T;
  capabilities?:
    | T
    | {
        item?: T;
        id?: T;
      };
  projectCount?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manifesto-statements_select".
 */
export interface ManifestoStatementsSelect<T extends boolean = true> {
  text?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              line1?: T;
              line2?: T;
              locationLine?: T;
              scrollCue?: T;
              orbitEnabled?: T;
              id?: T;
              blockName?: T;
            };
        manifestoStrip?:
          | T
          | {
              heading?: T;
              id?: T;
              blockName?: T;
            };
        featuredWorks?:
          | T
          | {
              heading?: T;
              id?: T;
              blockName?: T;
            };
        servicesRows?:
          | T
          | {
              heading?: T;
              id?: T;
              blockName?: T;
            };
        archiveTeaser?:
          | T
          | {
              countTemplate?: T;
              id?: T;
              blockName?: T;
            };
        contactMailto?:
          | T
          | {
              heading?: T;
              emailOverride?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        mediaFull?:
          | T
          | {
              media?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  region?: T;
  lat?: T;
  lng?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businesses_select".
 */
export interface BusinessesSelect<T extends boolean = true> {
  name?: T;
  city?: T;
  kind?: T;
  website?: T;
  foundedYear?: T;
  planet?:
    | T
    | {
        size?: T;
        pattern?: T;
        ink?: T;
      };
  trail?:
    | T
    | {
        style?: T;
        length?: T;
      };
  orbit?: T;
  status?: T;
  contactEmail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  email?: string | null;
  locationLine?: string | null;
  /**
   * IANA timezone for the live clock in the contact section
   */
  timezone?: string | null;
  socials?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Labels for the numbered nav (001/002/003 numbering is automatic)
   */
  navLabels?: {
    home?: string | null;
    manifesto?: string | null;
    archive?: string | null;
  };
  archiveCountTemplate?: string | null;
  /**
   * Vocabulary band on the manifesto page — 8 to 12 short words reads best. Order is the setting: they are laid out in this order.
   */
  marginNotes?:
    | {
        word: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-effects".
 */
export interface HeroEffect {
  id: number;
  /**
   * Lets visitors press and hold the logo to pull it apart. Turning this off keeps the glass look, hatching and light wash — it only disables the interaction.
   */
  separationEnabled?: boolean | null;
  /**
   * How long the charge and the reassembly take
   */
  timing?: {
    chargeMs?: number | null;
    reformMs?: number | null;
    /**
     * Fraction of the charge that passes before anything moves
     */
    separateStart?: number | null;
    staggerMax?: number | null;
  };
  /**
   * How far and how the six faces travel
   */
  motion?: {
    /**
     * Drift distance as a multiple of logo height. Above ~1.0 the faces leave the screen before you can watch them.
     */
    spreadFrac?: number | null;
    spreadVar?: number | null;
    lateralDrift?: number | null;
    spinMin?: number | null;
    spinMax?: number | null;
    /**
     * Cutoff deciding whether a surface is a flat face or a side wall
     */
    capNormalMin?: number | null;
  };
  /**
   * Pencil hatching and the sweeping light wash
   */
  material?: {
    normalFollow?: number | null;
    hatchStrength?: number | null;
    /**
     * Higher = coarser strokes, lower = denser
     */
    hatchScale?: number | null;
    shineStrength?: number | null;
    shineWidth?: number | null;
    shineSpeed?: number | null;
    shineChargeBoost?: number | null;
    /**
     * Warm end of the light wash, 6-digit hex
     */
    shineWarm?: string | null;
    /**
     * Hot end of the light wash, 6-digit hex
     */
    shineBright?: string | null;
  };
  /**
   * The glass skin and the ghost logo left behind
   */
  body?: {
    /**
     * Below ~0.5 the black and red wash out against the paper background.
     */
    skinOpacity?: number | null;
    /**
     * At 0 only the wireframe outline of the ghost logo is drawn
     */
    bodyOpacity?: number | null;
    bodyEdgeOpacity?: number | null;
    /**
     * Degrees. Lower draws more edges and gets noisy quickly.
     */
    bodyEdgeAngle?: number | null;
  };
  /**
   * Shake while charging, and drag sensitivity
   */
  feel?: {
    vibrateFrac?: number | null;
    vibratePhaseStep?: number | null;
    /**
     * Pointer travel that turns a hold into a drag
     */
    dragThresholdPx?: number | null;
  };
  /**
   * Plays the electrical wireframe transition between the sketch video and the rotating 3D logo. Turning this off restores the plain crossfade.
   */
  ignitionEnabled?: boolean | null;
  /**
   * Total length, and the phase boundaries as fractions of it. Changing the duration retimes everything proportionally.
   */
  ignitionTiming?: {
    /**
     * Total length of the transition. The main pacing control.
     */
    ignitionMs?: number | null;
    /**
     * Fraction where the core bloom ends and the front starts moving
     */
    seedEnd?: number | null;
    /**
     * Fraction where the charge front finishes crossing the logo
     */
    frontEnd?: number | null;
    /**
     * Fraction where the floating words / orbs are told to enter
     */
    cueFrac?: number | null;
  };
  /**
   * Where the charge starts and how wide its crest is
   */
  ignitionShape?: {
    seedOffsetX?: number | null;
    seedOffsetY?: number | null;
    seedOffsetZ?: number | null;
    /**
     * Width of the glowing crest, as a fraction of logo height
     */
    frontSoftness?: number | null;
    /**
     * How far behind the crest the solid surfaces appear
     */
    wakeLag?: number | null;
    coreRadius?: number | null;
    coreStrength?: number | null;
  };
  /**
   * The scribble wireframe that carries the charge
   */
  ignitionCage?: {
    /**
     * Fraction of wireframe lines drawn. At 1 it looks like CAD; lower reads as pencil scribble.
     */
    cageDensity?: number | null;
    /**
     * Same, on screens below 640px
     */
    cageDensityMobile?: number | null;
    cageOpacity?: number | null;
    /**
     * Changes which lines are drawn. Same number = same cage every load.
     */
    cageSeed?: number | null;
  };
  /**
   * The graphite-to-hot ramp, and the dark mass that makes red readable
   */
  ignitionColor?: {
    /**
     * Unlit cage — matches the pencil in the sketch video
     */
    coldColor?: string | null;
    warmColor?: string | null;
    hotColor?: string | null;
    /**
     * The very peak of the charge. Kept small and brief.
     */
    crestColor?: string | null;
    /**
     * Faint dark fill shown only during the transition. Without it the red washes out against the paper background.
     */
    darkMassOpacity?: number | null;
    glowDecay?: number | null;
  };
  /**
   * The cage appears over the still-drawing sketch video as a sphere, blooms outward into a polygon, then collapses into the logo shape.
   */
  ignitionOverlay?: {
    /**
     * Turning this off starts the transition at the video cut instead, with no sphere beforehand.
     */
    overlayEnabled?: boolean | null;
    /**
     * How long before the video ends the sphere appears
     */
    overlayLeadMs?: number | null;
    /**
     * Starting sphere size, as a multiple of the logo
     */
    sphereScale?: number | null;
    /**
     * The cage's TOTAL size when fully bloomed, as a multiple of the logo — measured corner to corner. Both this and the sphere are measured against the logo, so this number IS the final size rather than a multiplier on the sphere. Anything below the sphere size is raised to it.
     */
    bloomScale?: number | null;
    /**
     * Shape it blooms into. 8 is an octagon, 6 a hexagon.
     */
    polySides?: number | null;
    bloomStart?: number | null;
    bloomEnd?: number | null;
    /**
     * When the bloomed shape starts collapsing into the logo
     */
    morphStart?: number | null;
  };
  /**
   * Re-ignites while a visitor holds the logo and its skin peels away
   */
  ignitionPulse?: {
    pulseEnabled?: boolean | null;
    /**
     * Length of one pulse, and the gap before the next
     */
    pulseMs?: number | null;
  };
  /**
   * How much the cage writhes, and how it crackles
   */
  ignitionLife?: {
    /**
     * How far the wires drift, as a fraction of the logo radius
     */
    wireJitter?: number | null;
    wireSpeed?: number | null;
    /**
     * Randomness in the charge front. 0 gives a clean, even ring.
     */
    sparkStagger?: number | null;
    sparkRate?: number | null;
    /**
     * How many wires are lit at once. High values wash out.
     */
    sparkDensity?: number | null;
    /**
     * Sparking while the cage is still cold, over the video
     */
    sparkIdle?: number | null;
  };
  /**
   * Glowing particles at the cage junctions
   */
  ignitionEmbers?: {
    emberEnabled?: boolean | null;
    /**
     * Fraction of cage junctions that carry an ember
     */
    emberDensity?: number | null;
    emberSize?: number | null;
    emberTwinkle?: number | null;
    emberOpacity?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  email?: T;
  locationLine?: T;
  timezone?: T;
  socials?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  navLabels?:
    | T
    | {
        home?: T;
        manifesto?: T;
        archive?: T;
      };
  archiveCountTemplate?: T;
  marginNotes?:
    | T
    | {
        word?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-effects_select".
 */
export interface HeroEffectsSelect<T extends boolean = true> {
  separationEnabled?: T;
  timing?:
    | T
    | {
        chargeMs?: T;
        reformMs?: T;
        separateStart?: T;
        staggerMax?: T;
      };
  motion?:
    | T
    | {
        spreadFrac?: T;
        spreadVar?: T;
        lateralDrift?: T;
        spinMin?: T;
        spinMax?: T;
        capNormalMin?: T;
      };
  material?:
    | T
    | {
        normalFollow?: T;
        hatchStrength?: T;
        hatchScale?: T;
        shineStrength?: T;
        shineWidth?: T;
        shineSpeed?: T;
        shineChargeBoost?: T;
        shineWarm?: T;
        shineBright?: T;
      };
  body?:
    | T
    | {
        skinOpacity?: T;
        bodyOpacity?: T;
        bodyEdgeOpacity?: T;
        bodyEdgeAngle?: T;
      };
  feel?:
    | T
    | {
        vibrateFrac?: T;
        vibratePhaseStep?: T;
        dragThresholdPx?: T;
      };
  ignitionEnabled?: T;
  ignitionTiming?:
    | T
    | {
        ignitionMs?: T;
        seedEnd?: T;
        frontEnd?: T;
        cueFrac?: T;
      };
  ignitionShape?:
    | T
    | {
        seedOffsetX?: T;
        seedOffsetY?: T;
        seedOffsetZ?: T;
        frontSoftness?: T;
        wakeLag?: T;
        coreRadius?: T;
        coreStrength?: T;
      };
  ignitionCage?:
    | T
    | {
        cageDensity?: T;
        cageDensityMobile?: T;
        cageOpacity?: T;
        cageSeed?: T;
      };
  ignitionColor?:
    | T
    | {
        coldColor?: T;
        warmColor?: T;
        hotColor?: T;
        crestColor?: T;
        darkMassOpacity?: T;
        glowDecay?: T;
      };
  ignitionOverlay?:
    | T
    | {
        overlayEnabled?: T;
        overlayLeadMs?: T;
        sphereScale?: T;
        bloomScale?: T;
        polySides?: T;
        bloomStart?: T;
        bloomEnd?: T;
        morphStart?: T;
      };
  ignitionPulse?:
    | T
    | {
        pulseEnabled?: T;
        pulseMs?: T;
      };
  ignitionLife?:
    | T
    | {
        wireJitter?: T;
        wireSpeed?: T;
        sparkStagger?: T;
        sparkRate?: T;
        sparkDensity?: T;
        sparkIdle?: T;
      };
  ignitionEmbers?:
    | T
    | {
        emberEnabled?: T;
        emberDensity?: T;
        emberSize?: T;
        emberTwinkle?: T;
        emberOpacity?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}