/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    works: Work;
    services: Service;
    'manifesto-statements': ManifestoStatement;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    works: WorksSelect<false> | WorksSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'manifesto-statements': ManifestoStatementsSelect<false> | ManifestoStatementsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'id') | ('en' | 'id')[];
  globals: {
    'site-settings': SiteSetting;
    'hero-effects': HeroEffect;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'hero-effects': HeroEffectsSelect<false> | HeroEffectsSelect<true>;
  };
  locale: 'en' | 'id';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works".
 */
export interface Work {
  id: number;
  title: string;
  slug: string;
  category: 'brand' | 'web' | 'motion' | 'engineering';
  year: number;
  /**
   * One-sentence description — shown as "// 01 Description" in the homepage works carousel
   */
  oneLiner?: string | null;
  /**
   * Comma-separated services list — "// 02 Services" in the works carousel (e.g. "Art Direction, Motion Graphics")
   */
  servicesLine?: string | null;
  /**
   * "// 03 Industry" in the works carousel
   */
  industry?: string | null;
  /**
   * "// 04 Location" in the works carousel
   */
  location?: string | null;
  cover?: (number | null) | Media;
  featured?: boolean | null;
  /**
   * Position on the drag-canvas archive (canvas units)
   */
  archiveSlot?: {
    x?: number | null;
    y?: number | null;
    scale?: number | null;
  };
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  /**
   * Bold headline inside the expanded row (e.g. "Shaping identities that resonate and endure")
   */
  tagline?: string | null;
  /**
   * Paragraph inside the expanded row
   */
  description?: string | null;
  capabilities?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown as "003//" on the row (manual for now — works aren’t related to services yet)
   */
  projectCount?: number | null;
  /**
   * Stroke icon shown next to the service name
   */
  icon?: ('strategy' | 'grid' | 'motion' | 'code' | 'pen' | 'layers' | 'camera' | 'spark') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manifesto-statements".
 */
export interface ManifestoStatement {
  id: number;
  text: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout?:
    | (
        | {
            line1: string;
            line2?: string | null;
            locationLine?: string | null;
            scrollCue?: string | null;
            /**
             * Floating "margin note" words tethered to the logo by pencil strings (decorative; hero looks complete without them)
             */
            constellationEnabled?: boolean | null;
            /**
             * 8–18 short words orbiting the logo, one satellite each — on every screen size. Colours are set per orbit slot under Hero Effects → Satellites.
             */
            floatingWords?:
              | {
                  word: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Heading above the chat box in the dark room. The box is a STUB — it is styled and positioned but does not send anything yet.
             */
            chatHeading?: string | null;
            /**
             * Placeholder inside the disabled input. Say what SAMSARA will eventually answer, so the stub reads as a promise rather than a broken field.
             */
            chatPlaceholder?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'samsaraRoom';
          }
        | {
            heading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'manifestoStrip';
          }
        | {
            heading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredWorks';
          }
        | {
            heading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'servicesRows';
          }
        | {
            countTemplate?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'archiveTeaser';
          }
        | {
            heading?: string | null;
            emailOverride?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactMailto';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            media?: (number | null) | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaFull';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'works';
        value: number | Work;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'manifesto-statements';
        value: number | ManifestoStatement;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works_select".
 */
export interface WorksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  year?: T;
  oneLiner?: T;
  servicesLine?: T;
  industry?: T;
  location?: T;
  cover?: T;
  featured?: T;
  archiveSlot?:
    | T
    | {
        x?: T;
        y?: T;
        scale?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  description?: T;
  capabilities?:
    | T
    | {
        item?: T;
        id?: T;
      };
  projectCount?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manifesto-statements_select".
 */
export interface ManifestoStatementsSelect<T extends boolean = true> {
  text?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              line1?: T;
              line2?: T;
              locationLine?: T;
              scrollCue?: T;
              constellationEnabled?: T;
              floatingWords?:
                | T
                | {
                    word?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        samsaraRoom?:
          | T
          | {
              chatHeading?: T;
              chatPlaceholder?: T;
              id?: T;
              blockName?: T;
            };
        manifestoStrip?:
          | T
          | {
              heading?: T;
              id?: T;
              blockName?: T;
            };
        featuredWorks?:
          | T
          | {
              heading?: T;
              id?: T;
              blockName?: T;
            };
        servicesRows?:
          | T
          | {
              heading?: T;
              id?: T;
              blockName?: T;
            };
        archiveTeaser?:
          | T
          | {
              countTemplate?: T;
              id?: T;
              blockName?: T;
            };
        contactMailto?:
          | T
          | {
              heading?: T;
              emailOverride?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        mediaFull?:
          | T
          | {
              media?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  email?: string | null;
  locationLine?: string | null;
  /**
   * IANA timezone for the live clock in the contact section
   */
  timezone?: string | null;
  socials?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Labels for the numbered nav (001/002/003 numbering is automatic)
   */
  navLabels?: {
    home?: string | null;
    manifesto?: string | null;
    archive?: string | null;
  };
  archiveCountTemplate?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-effects".
 */
export interface HeroEffect {
  id: number;
  /**
   * Lets visitors press and hold the logo to pull it apart. Turning this off keeps the glass look, hatching and light wash — it only disables the interaction.
   */
  separationEnabled?: boolean | null;
  /**
   * How long the charge and the reassembly take
   */
  timing?: {
    chargeMs?: number | null;
    reformMs?: number | null;
    /**
     * Fraction of the charge that passes before anything moves
     */
    separateStart?: number | null;
    staggerMax?: number | null;
  };
  /**
   * How far and how the six faces travel
   */
  motion?: {
    /**
     * Drift distance as a multiple of logo height. Above ~1.0 the faces leave the screen before you can watch them.
     */
    spreadFrac?: number | null;
    spreadVar?: number | null;
    lateralDrift?: number | null;
    spinMin?: number | null;
    spinMax?: number | null;
    /**
     * Cutoff deciding whether a surface is a flat face or a side wall
     */
    capNormalMin?: number | null;
  };
  /**
   * Pencil hatching and the sweeping light wash
   */
  material?: {
    normalFollow?: number | null;
    hatchStrength?: number | null;
    /**
     * Higher = coarser strokes, lower = denser
     */
    hatchScale?: number | null;
    shineStrength?: number | null;
    shineWidth?: number | null;
    shineSpeed?: number | null;
    shineChargeBoost?: number | null;
    /**
     * Warm end of the light wash, 6-digit hex
     */
    shineWarm?: string | null;
    /**
     * Hot end of the light wash, 6-digit hex
     */
    shineBright?: string | null;
  };
  /**
   * The glass skin and the ghost logo left behind
   */
  body?: {
    /**
     * Below ~0.5 the black and red wash out against the paper background.
     */
    skinOpacity?: number | null;
    /**
     * At 0 only the wireframe outline of the ghost logo is drawn
     */
    bodyOpacity?: number | null;
    bodyEdgeOpacity?: number | null;
    /**
     * Degrees. Lower draws more edges and gets noisy quickly.
     */
    bodyEdgeAngle?: number | null;
  };
  /**
   * Shake while charging, and drag sensitivity
   */
  feel?: {
    vibrateFrac?: number | null;
    vibratePhaseStep?: number | null;
    /**
     * Pointer travel that turns a hold into a drag
     */
    dragThresholdPx?: number | null;
  };
  /**
   * Plays the electrical wireframe transition between the sketch video and the rotating 3D logo. Turning this off restores the plain crossfade.
   */
  ignitionEnabled?: boolean | null;
  /**
   * Total length, and the phase boundaries as fractions of it. Changing the duration retimes everything proportionally.
   */
  ignitionTiming?: {
    /**
     * Total length of the transition. The main pacing control.
     */
    ignitionMs?: number | null;
    /**
     * Fraction where the core bloom ends and the front starts moving
     */
    seedEnd?: number | null;
    /**
     * Fraction where the charge front finishes crossing the logo
     */
    frontEnd?: number | null;
    /**
     * Fraction where the floating words / orbs are told to enter
     */
    cueFrac?: number | null;
  };
  /**
   * Where the charge starts and how wide its crest is
   */
  ignitionShape?: {
    seedOffsetX?: number | null;
    seedOffsetY?: number | null;
    seedOffsetZ?: number | null;
    /**
     * Width of the glowing crest, as a fraction of logo height
     */
    frontSoftness?: number | null;
    /**
     * How far behind the crest the solid surfaces appear
     */
    wakeLag?: number | null;
    coreRadius?: number | null;
    coreStrength?: number | null;
  };
  /**
   * The scribble wireframe that carries the charge
   */
  ignitionCage?: {
    /**
     * Fraction of wireframe lines drawn. At 1 it looks like CAD; lower reads as pencil scribble.
     */
    cageDensity?: number | null;
    /**
     * Same, on screens below 640px
     */
    cageDensityMobile?: number | null;
    cageOpacity?: number | null;
    /**
     * Changes which lines are drawn. Same number = same cage every load.
     */
    cageSeed?: number | null;
  };
  /**
   * The graphite-to-hot ramp, and the dark mass that makes red readable
   */
  ignitionColor?: {
    /**
     * Unlit cage — matches the pencil in the sketch video
     */
    coldColor?: string | null;
    warmColor?: string | null;
    hotColor?: string | null;
    /**
     * The very peak of the charge. Kept small and brief.
     */
    crestColor?: string | null;
    /**
     * Faint dark fill shown only during the transition. Without it the red washes out against the paper background.
     */
    darkMassOpacity?: number | null;
    glowDecay?: number | null;
  };
  /**
   * The cage appears over the still-drawing sketch video as a sphere, blooms outward into a polygon, then collapses into the logo shape.
   */
  ignitionOverlay?: {
    /**
     * Turning this off starts the transition at the video cut instead, with no sphere beforehand.
     */
    overlayEnabled?: boolean | null;
    /**
     * How long before the video ends the sphere appears
     */
    overlayLeadMs?: number | null;
    /**
     * Starting sphere size, as a multiple of the logo
     */
    sphereScale?: number | null;
    /**
     * The cage's TOTAL size when fully bloomed, as a multiple of the logo — measured corner to corner. Both this and the sphere are measured against the logo, so this number IS the final size rather than a multiplier on the sphere. Anything below the sphere size is raised to it.
     */
    bloomScale?: number | null;
    /**
     * Shape it blooms into. 8 is an octagon, 6 a hexagon.
     */
    polySides?: number | null;
    bloomStart?: number | null;
    bloomEnd?: number | null;
    /**
     * When the bloomed shape starts collapsing into the logo
     */
    morphStart?: number | null;
  };
  /**
   * Re-ignites while a visitor holds the logo and its skin peels away
   */
  ignitionPulse?: {
    pulseEnabled?: boolean | null;
    /**
     * Length of one pulse, and the gap before the next
     */
    pulseMs?: number | null;
  };
  /**
   * How much the cage writhes, and how it crackles
   */
  ignitionLife?: {
    /**
     * How far the wires drift, as a fraction of the logo radius
     */
    wireJitter?: number | null;
    wireSpeed?: number | null;
    /**
     * Randomness in the charge front. 0 gives a clean, even ring.
     */
    sparkStagger?: number | null;
    sparkRate?: number | null;
    /**
     * How many wires are lit at once. High values wash out.
     */
    sparkDensity?: number | null;
    /**
     * Sparking while the cage is still cold, over the video
     */
    sparkIdle?: number | null;
  };
  /**
   * Glowing particles at the cage junctions
   */
  ignitionEmbers?: {
    emberEnabled?: boolean | null;
    /**
     * Fraction of cage junctions that carry an ember
     */
    emberDensity?: number | null;
    emberSize?: number | null;
    emberTwinkle?: number | null;
    emberOpacity?: number | null;
  };
  /**
   * Coloured spheres orbiting the logo, each carrying one of the hero words. Turning this off removes them entirely — the hero keeps the logo, the video and the headline.
   */
  satellitesEnabled?: boolean | null;
  /**
   * Where the belt sits relative to the mark
   */
  satelliteField?: {
    /**
     * Orbit floor, as a multiple of the logo’s on-screen half-height
     */
    innerRadius?: number | null;
    /**
     * Reference radius, as a fraction of half the viewport’s smaller side. Satellites orbit inside a band of this — see “band inner/outer” below.
     */
    outerRadius?: number | null;
    mobileInnerRadius?: number | null;
    /**
     * Used below 640px. The desktop value leaves only about half the belt on a portrait screen.
     */
    mobileOuterRadius?: number | null;
    /**
     * Inclination in degrees. 0 is edge-on, 90 is face-on.
     */
    tilt?: number | null;
    tiltSideway?: number | null;
    /**
     * Lower is a stronger perspective
     */
    perspective?: number | null;
  };
  satelliteMotion?: {
    orbitSpeed?: number | null;
    /**
     * Counter-clockwise on screen. Off runs them clockwise.
     */
    orbitCcw?: boolean | null;
    speedScale?: number | null;
    /**
     * 0 leaves no trail, 50 is the longest streak
     */
    trail?: number | null;
  };
  satelliteLook?: {
    size?: number | null;
    alpha?: number | null;
    /**
     * 0 is a flat disc, 1 is a fully modelled sphere
     */
    shade?: number | null;
    /**
     * Extra near/far size difference beyond the perspective divide
     */
    depthScale?: number | null;
    streak?: number | null;
    /**
     * Outline radius as a multiple of the sphere. 0 removes it.
     */
    ring?: number | null;
    /**
     * Innermost satellite orbit, as a fraction of the outer radius
     */
    bandInner?: number | null;
    bandOuter?: number | null;
    /**
     * Per-satellite inclination variation, in degrees. 0 is one shared plane.
     */
    tiltSpread?: number | null;
    /**
     * Used for any satellite the colour list below does not cover
     */
    baseColor?: string | null;
  };
  /**
   * Colour belongs to the ORBIT SLOT, not to the word: the first row colours the first satellite regardless of which word it carries, and regardless of language. Reordering the hero words does NOT reorder these. Extra rows are ignored; satellites past the last row use the base colour above.
   */
  satelliteColors?:
    | {
        color: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The words themselves are the hero block’s “floating words” on the Home page, and the number of satellites follows that list.
   */
  satelliteLabels?: {
    mode?: ('always' | 'hover' | 'none') | null;
    size?: number | null;
    color?: string | null;
    offset?: number | null;
    hoverRadius?: number | null;
  };
  /**
   * What the satellites do while a visitor holds the logo. Shares the same gesture as the hold-to-separate effect above.
   */
  satelliteHold?: {
    /**
     * Stop orbiting and tremble in place while the logo is held
     */
    freeze?: boolean | null;
    shakePx?: number | null;
    shakeSpeed?: number | null;
  };
  satelliteBehaviour?: {
    entranceMs?: number | null;
    /**
     * Screens of scrolling over which the field dissolves. 0 never fades.
     */
    scrollFadeVh?: number | null;
    /**
     * Changing this reshuffles the starting arrangement
     */
    seed?: number | null;
  };
  /**
   * A single brass mascot orbiting the logo alongside the satellites, trailing gold dust and carrying its own word. Turning this off removes it entirely — nothing else in the hero changes.
   */
  mascotEnabled?: boolean | null;
  /**
   * The mascot’s word. NOT one of the hero “floating words” — those are localized and their count drives the satellites; this is the mascot’s own fixed name, shown identically in both languages.
   */
  mascotLabelText?: string | null;
  /**
   * The mascot shares the satellites’ orbital plane (tilt, roll, direction). These are its own place within it.
   */
  mascotOrbit?: {
    /**
     * As a fraction of the satellites’ outer radius. The bead band is 0.5–0.8.
     */
    radius?: number | null;
    mobileRadius?: number | null;
    /**
     * How far the mascot rides above the belt plane, in px. Keep this well clear of 0 — it is what keeps the mascot reading as nearer than the beads it passes.
     */
    height?: number | null;
    tiltOffset?: number | null;
    /**
     * Starting angle on the orbit, degrees
     */
    phase?: number | null;
    /**
     * Orbit speed as a multiple of the satellites’ orbit speed
     */
    speedScale?: number | null;
  };
  mascotLook?: {
    /**
     * On-screen diameter in px at zero depth
     */
    size?: number | null;
    mobileSize?: number | null;
    /**
     * Extra near/far size difference beyond the perspective divide. NOT the satellites’ 0.9 — that value is tuned for 4px beads.
     */
    depthScale?: number | null;
    opacity?: number | null;
    /**
     * Reflection strength. Brass is fully metallic — at 0 it goes black.
     */
    envIntensity?: number | null;
    lightIntensity?: number | null;
  };
  mascotSpin?: {
    /**
     * Degrees per second, independent of the orbit
     */
    spinSpeed?: number | null;
    spinTilt?: number | null;
    /**
     * Slow vertical float on top of the orbit
     */
    bobPx?: number | null;
    bobSeconds?: number | null;
  };
  /**
   * A shed particle field. Additive blending is a deliberate choice — the dust colour is picked bright to suit it.
   */
  mascotTrail?: {
    enabled?: boolean | null;
    /**
     * How long each mote lives
     */
    seconds?: number | null;
    /**
     * Motes per second
     */
    density?: number | null;
    /**
     * Mote diameter in px
     */
    size?: number | null;
    /**
     * Random scatter at emission, px
     */
    spread?: number | null;
    /**
     * How fast motes drift off the path, px/sec
     */
    drift?: number | null;
    /**
     * Hot-core strength
     */
    glow?: number | null;
    twinkle?: number | null;
    opacity?: number | null;
    /**
     * Additive blending. Off is slightly more saturated on the paper.
     */
    additive?: boolean | null;
    /**
     * The saturated body of each mote
     */
    color?: string | null;
    /**
     * The bright centre of each mote
     */
    coreColor?: string | null;
  };
  /**
   * The word’s text is set above (“mascot label text”). These control how it looks.
   */
  mascotLabel?: {
    enabled?: boolean | null;
    size?: number | null;
    color?: string | null;
    /**
     * Gap from the mascot’s edge, px
     */
    offset?: number | null;
    /**
     * Paper-coloured halo behind the word, px. Fixes the word going illegible where it crosses the mark’s red stroke. 0 is off.
     */
    halo?: number | null;
  };
  /**
   * Shares the same gesture as the hold-to-separate effect. Freeze + tremble in place while the logo is held.
   */
  mascotHold?: {
    freeze?: boolean | null;
    shakePx?: number | null;
    shakeSpeed?: number | null;
  };
  mascotBehaviour?: {
    entranceMs?: number | null;
    /**
     * Screens of scrolling over which the mascot dissolves. 0 never fades.
     */
    scrollFadeVh?: number | null;
  };
  /**
   * The mascot’s animated LED face. Turning this off restores its original painted eyes exactly — no socket darkening, no display. The expression shapes are not editable here: they were tuned on screen and are frozen in code, so changing one is a code change.
   */
  mascotEyesEnabled?: boolean | null;
  mascotEyesLook?: {
    /**
     * The lit eye. Amber rather than the reference’s cyan, so the hero keeps one warm accent instead of gaining a second, cold one.
     */
    color?: string | null;
    /**
     * Hot centre of the eye.
     */
    coreColor?: string | null;
    /**
     * Darkening over the faceplate. It exists to cover the mascot’s own PAINTED amber ovals — lighten it and the old eyes show through around the new ones.
     */
    socketColor?: string | null;
    glow?: number | null;
    /**
     * Half-distance between the two eyes.
     */
    gap?: number | null;
    /**
     * How far the darkening reaches. ⚠️ Anything drawn past this is CUT with a hard edge, not faded, and at 1.34 there is no headroom left — one expression already reaches 1.35. Raise this, never lower it.
     */
    socketSpan?: number | null;
  };
  mascotEyesScanlines?: {
    max?: number | null;
    /**
     * Body size below which scanlines are off. Deliberately above the mascot’s 28px base, so they appear only as it swings near — 7 lines over an 18px eye is moire, not texture.
     */
    minBodyPx?: number | null;
    ramp?: number | null;
  };
  /**
   * The mascot plays ONE expression each time its face sweeps past the viewer, then returns to neutral. There is no idle timer and no cursor tracking — the face is only toward you about a quarter of each turn.
   */
  mascotEyesBeat?: {
    glanceSeconds?: number | null;
    /**
     * Where in the glance the expression peaks.
     */
    glancePeak?: number | null;
    /**
     * How square-on the face must be to count as facing you.
     */
    facingThreshold?: number | null;
    /**
     * While the mark is held: the eyes widen, then squeeze shut past this point.
     */
    chargeCrossover?: number | null;
    noRepeat?: boolean | null;
  };
  /**
   * How often each expression is picked. 0 removes it entirely. “Neutral” is the resting face and “wide” belongs to the press-and-hold reaction, so both are 0 here by design.
   */
  mascotEyesWeights?: {
    neutral?: number | null;
    blink?: number | null;
    squint?: number | null;
    wide?: number | null;
    happy?: number | null;
    lookLeft?: number | null;
    lookRight?: number | null;
    lookUp?: number | null;
    lookDown?: number | null;
    lookUpLeft?: number | null;
    lookUpRight?: number | null;
    lookDownLeft?: number | null;
    lookDownRight?: number | null;
    wink?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  email?: T;
  locationLine?: T;
  timezone?: T;
  socials?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  navLabels?:
    | T
    | {
        home?: T;
        manifesto?: T;
        archive?: T;
      };
  archiveCountTemplate?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-effects_select".
 */
export interface HeroEffectsSelect<T extends boolean = true> {
  separationEnabled?: T;
  timing?:
    | T
    | {
        chargeMs?: T;
        reformMs?: T;
        separateStart?: T;
        staggerMax?: T;
      };
  motion?:
    | T
    | {
        spreadFrac?: T;
        spreadVar?: T;
        lateralDrift?: T;
        spinMin?: T;
        spinMax?: T;
        capNormalMin?: T;
      };
  material?:
    | T
    | {
        normalFollow?: T;
        hatchStrength?: T;
        hatchScale?: T;
        shineStrength?: T;
        shineWidth?: T;
        shineSpeed?: T;
        shineChargeBoost?: T;
        shineWarm?: T;
        shineBright?: T;
      };
  body?:
    | T
    | {
        skinOpacity?: T;
        bodyOpacity?: T;
        bodyEdgeOpacity?: T;
        bodyEdgeAngle?: T;
      };
  feel?:
    | T
    | {
        vibrateFrac?: T;
        vibratePhaseStep?: T;
        dragThresholdPx?: T;
      };
  ignitionEnabled?: T;
  ignitionTiming?:
    | T
    | {
        ignitionMs?: T;
        seedEnd?: T;
        frontEnd?: T;
        cueFrac?: T;
      };
  ignitionShape?:
    | T
    | {
        seedOffsetX?: T;
        seedOffsetY?: T;
        seedOffsetZ?: T;
        frontSoftness?: T;
        wakeLag?: T;
        coreRadius?: T;
        coreStrength?: T;
      };
  ignitionCage?:
    | T
    | {
        cageDensity?: T;
        cageDensityMobile?: T;
        cageOpacity?: T;
        cageSeed?: T;
      };
  ignitionColor?:
    | T
    | {
        coldColor?: T;
        warmColor?: T;
        hotColor?: T;
        crestColor?: T;
        darkMassOpacity?: T;
        glowDecay?: T;
      };
  ignitionOverlay?:
    | T
    | {
        overlayEnabled?: T;
        overlayLeadMs?: T;
        sphereScale?: T;
        bloomScale?: T;
        polySides?: T;
        bloomStart?: T;
        bloomEnd?: T;
        morphStart?: T;
      };
  ignitionPulse?:
    | T
    | {
        pulseEnabled?: T;
        pulseMs?: T;
      };
  ignitionLife?:
    | T
    | {
        wireJitter?: T;
        wireSpeed?: T;
        sparkStagger?: T;
        sparkRate?: T;
        sparkDensity?: T;
        sparkIdle?: T;
      };
  ignitionEmbers?:
    | T
    | {
        emberEnabled?: T;
        emberDensity?: T;
        emberSize?: T;
        emberTwinkle?: T;
        emberOpacity?: T;
      };
  satellitesEnabled?: T;
  satelliteField?:
    | T
    | {
        innerRadius?: T;
        outerRadius?: T;
        mobileInnerRadius?: T;
        mobileOuterRadius?: T;
        tilt?: T;
        tiltSideway?: T;
        perspective?: T;
      };
  satelliteMotion?:
    | T
    | {
        orbitSpeed?: T;
        orbitCcw?: T;
        speedScale?: T;
        trail?: T;
      };
  satelliteLook?:
    | T
    | {
        size?: T;
        alpha?: T;
        shade?: T;
        depthScale?: T;
        streak?: T;
        ring?: T;
        bandInner?: T;
        bandOuter?: T;
        tiltSpread?: T;
        baseColor?: T;
      };
  satelliteColors?:
    | T
    | {
        color?: T;
        id?: T;
      };
  satelliteLabels?:
    | T
    | {
        mode?: T;
        size?: T;
        color?: T;
        offset?: T;
        hoverRadius?: T;
      };
  satelliteHold?:
    | T
    | {
        freeze?: T;
        shakePx?: T;
        shakeSpeed?: T;
      };
  satelliteBehaviour?:
    | T
    | {
        entranceMs?: T;
        scrollFadeVh?: T;
        seed?: T;
      };
  mascotEnabled?: T;
  mascotLabelText?: T;
  mascotOrbit?:
    | T
    | {
        radius?: T;
        mobileRadius?: T;
        height?: T;
        tiltOffset?: T;
        phase?: T;
        speedScale?: T;
      };
  mascotLook?:
    | T
    | {
        size?: T;
        mobileSize?: T;
        depthScale?: T;
        opacity?: T;
        envIntensity?: T;
        lightIntensity?: T;
      };
  mascotSpin?:
    | T
    | {
        spinSpeed?: T;
        spinTilt?: T;
        bobPx?: T;
        bobSeconds?: T;
      };
  mascotTrail?:
    | T
    | {
        enabled?: T;
        seconds?: T;
        density?: T;
        size?: T;
        spread?: T;
        drift?: T;
        glow?: T;
        twinkle?: T;
        opacity?: T;
        additive?: T;
        color?: T;
        coreColor?: T;
      };
  mascotLabel?:
    | T
    | {
        enabled?: T;
        size?: T;
        color?: T;
        offset?: T;
        halo?: T;
      };
  mascotHold?:
    | T
    | {
        freeze?: T;
        shakePx?: T;
        shakeSpeed?: T;
      };
  mascotBehaviour?:
    | T
    | {
        entranceMs?: T;
        scrollFadeVh?: T;
      };
  mascotEyesEnabled?: T;
  mascotEyesLook?:
    | T
    | {
        color?: T;
        coreColor?: T;
        socketColor?: T;
        glow?: T;
        gap?: T;
        socketSpan?: T;
      };
  mascotEyesScanlines?:
    | T
    | {
        max?: T;
        minBodyPx?: T;
        ramp?: T;
      };
  mascotEyesBeat?:
    | T
    | {
        glanceSeconds?: T;
        glancePeak?: T;
        facingThreshold?: T;
        chargeCrossover?: T;
        noRepeat?: T;
      };
  mascotEyesWeights?:
    | T
    | {
        neutral?: T;
        blink?: T;
        squint?: T;
        wide?: T;
        happy?: T;
        lookLeft?: T;
        lookRight?: T;
        lookUp?: T;
        lookDown?: T;
        lookUpLeft?: T;
        lookUpRight?: T;
        lookDownLeft?: T;
        lookDownRight?: T;
        wink?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}