/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    works: Work;
    services: Service;
    'manifesto-statements': ManifestoStatement;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    works: WorksSelect<false> | WorksSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'manifesto-statements': ManifestoStatementsSelect<false> | ManifestoStatementsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'id') | ('en' | 'id')[];
  globals: {
    'site-settings': SiteSetting;
    'hero-effects': HeroEffect;
    'samsara-sequence': SamsaraSequence;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'hero-effects': HeroEffectsSelect<false> | HeroEffectsSelect<true>;
    'samsara-sequence': SamsaraSequenceSelect<false> | SamsaraSequenceSelect<true>;
  };
  locale: 'en' | 'id';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works".
 */
export interface Work {
  id: number;
  title: string;
  slug: string;
  category: 'brand' | 'web' | 'motion' | 'engineering';
  year: number;
  /**
   * One-sentence description — shown as "// 01 Description" in the homepage works carousel
   */
  oneLiner?: string | null;
  /**
   * Comma-separated services list — "// 02 Services" in the works carousel (e.g. "Art Direction, Motion Graphics")
   */
  servicesLine?: string | null;
  /**
   * "// 03 Industry" in the works carousel
   */
  industry?: string | null;
  /**
   * "// 04 Location" in the works carousel
   */
  location?: string | null;
  cover?: (number | null) | Media;
  featured?: boolean | null;
  /**
   * Position on the drag-canvas archive (canvas units)
   */
  archiveSlot?: {
    x?: number | null;
    y?: number | null;
    scale?: number | null;
  };
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  /**
   * Bold headline inside the expanded row (e.g. "Shaping identities that resonate and endure")
   */
  tagline?: string | null;
  /**
   * Paragraph inside the expanded row
   */
  description?: string | null;
  capabilities?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown as "003//" on the row (manual for now — works aren’t related to services yet)
   */
  projectCount?: number | null;
  /**
   * Stroke icon shown next to the service name
   */
  icon?: ('strategy' | 'grid' | 'motion' | 'code' | 'pen' | 'layers' | 'camera' | 'spark') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manifesto-statements".
 */
export interface ManifestoStatement {
  id: number;
  text: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout?:
    | (
        | {
            line1: string;
            line2?: string | null;
            locationLine?: string | null;
            scrollCue?: string | null;
            /**
             * Floating "margin note" words tethered to the logo by pencil strings (decorative; hero looks complete without them)
             */
            constellationEnabled?: boolean | null;
            /**
             * 8–18 short words orbiting the logo, one satellite each — on every screen size. Colours are set per orbit slot under Hero Effects → Satellites.
             */
            floatingWords?:
              | {
                  word: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'samsaraRoom';
          }
        | {
            heading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'manifestoStrip';
          }
        | {
            heading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredWorks';
          }
        | {
            heading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'servicesRows';
          }
        | {
            countTemplate?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'archiveTeaser';
          }
        | {
            heading?: string | null;
            emailOverride?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactMailto';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            media?: (number | null) | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaFull';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'works';
        value: number | Work;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'manifesto-statements';
        value: number | ManifestoStatement;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works_select".
 */
export interface WorksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  year?: T;
  oneLiner?: T;
  servicesLine?: T;
  industry?: T;
  location?: T;
  cover?: T;
  featured?: T;
  archiveSlot?:
    | T
    | {
        x?: T;
        y?: T;
        scale?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  description?: T;
  capabilities?:
    | T
    | {
        item?: T;
        id?: T;
      };
  projectCount?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manifesto-statements_select".
 */
export interface ManifestoStatementsSelect<T extends boolean = true> {
  text?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              line1?: T;
              line2?: T;
              locationLine?: T;
              scrollCue?: T;
              constellationEnabled?: T;
              floatingWords?:
                | T
                | {
                    word?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        samsaraRoom?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        manifestoStrip?:
          | T
          | {
              heading?: T;
              id?: T;
              blockName?: T;
            };
        featuredWorks?:
          | T
          | {
              heading?: T;
              id?: T;
              blockName?: T;
            };
        servicesRows?:
          | T
          | {
              heading?: T;
              id?: T;
              blockName?: T;
            };
        archiveTeaser?:
          | T
          | {
              countTemplate?: T;
              id?: T;
              blockName?: T;
            };
        contactMailto?:
          | T
          | {
              heading?: T;
              emailOverride?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        mediaFull?:
          | T
          | {
              media?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  email?: string | null;
  locationLine?: string | null;
  /**
   * IANA timezone for the live clock in the contact section
   */
  timezone?: string | null;
  socials?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Labels for the numbered nav (001/002/003 numbering is automatic)
   */
  navLabels?: {
    home?: string | null;
    manifesto?: string | null;
    archive?: string | null;
  };
  archiveCountTemplate?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-effects".
 */
export interface HeroEffect {
  id: number;
  /**
   * Lets visitors press and hold the logo to pull it apart. Turning this off keeps the glass look, hatching and light wash — it only disables the interaction.
   */
  separationEnabled?: boolean | null;
  /**
   * How long the charge and the reassembly take
   */
  timing?: {
    chargeMs?: number | null;
    reformMs?: number | null;
    /**
     * Fraction of the charge that passes before anything moves
     */
    separateStart?: number | null;
    staggerMax?: number | null;
  };
  /**
   * How far and how the six faces travel
   */
  motion?: {
    /**
     * Drift distance as a multiple of logo height. Above ~1.0 the faces leave the screen before you can watch them.
     */
    spreadFrac?: number | null;
    spreadVar?: number | null;
    lateralDrift?: number | null;
    spinMin?: number | null;
    spinMax?: number | null;
    /**
     * Cutoff deciding whether a surface is a flat face or a side wall
     */
    capNormalMin?: number | null;
  };
  /**
   * Pencil hatching and the sweeping light wash
   */
  material?: {
    normalFollow?: number | null;
    hatchStrength?: number | null;
    /**
     * Higher = coarser strokes, lower = denser
     */
    hatchScale?: number | null;
    shineStrength?: number | null;
    shineWidth?: number | null;
    shineSpeed?: number | null;
    shineChargeBoost?: number | null;
    /**
     * Warm end of the light wash, 6-digit hex
     */
    shineWarm?: string | null;
    /**
     * Hot end of the light wash, 6-digit hex
     */
    shineBright?: string | null;
  };
  /**
   * The glass skin and the ghost logo left behind
   */
  body?: {
    /**
     * Below ~0.5 the black and red wash out against the paper background.
     */
    skinOpacity?: number | null;
    /**
     * At 0 only the wireframe outline of the ghost logo is drawn
     */
    bodyOpacity?: number | null;
    bodyEdgeOpacity?: number | null;
    /**
     * Degrees. Lower draws more edges and gets noisy quickly.
     */
    bodyEdgeAngle?: number | null;
  };
  /**
   * Shake while charging, and drag sensitivity
   */
  feel?: {
    vibrateFrac?: number | null;
    vibratePhaseStep?: number | null;
    /**
     * Pointer travel that turns a hold into a drag
     */
    dragThresholdPx?: number | null;
  };
  /**
   * Plays the electrical wireframe transition between the sketch video and the rotating 3D logo. Turning this off restores the plain crossfade.
   */
  ignitionEnabled?: boolean | null;
  /**
   * Total length, and the phase boundaries as fractions of it. Changing the duration retimes everything proportionally.
   */
  ignitionTiming?: {
    /**
     * Total length of the transition. The main pacing control.
     */
    ignitionMs?: number | null;
    /**
     * Fraction where the core bloom ends and the front starts moving
     */
    seedEnd?: number | null;
    /**
     * Fraction where the charge front finishes crossing the logo
     */
    frontEnd?: number | null;
    /**
     * Fraction where the floating words / orbs are told to enter
     */
    cueFrac?: number | null;
  };
  /**
   * Where the charge starts and how wide its crest is
   */
  ignitionShape?: {
    seedOffsetX?: number | null;
    seedOffsetY?: number | null;
    seedOffsetZ?: number | null;
    /**
     * Width of the glowing crest, as a fraction of logo height
     */
    frontSoftness?: number | null;
    /**
     * How far behind the crest the solid surfaces appear
     */
    wakeLag?: number | null;
    coreRadius?: number | null;
    coreStrength?: number | null;
  };
  /**
   * The scribble wireframe that carries the charge
   */
  ignitionCage?: {
    /**
     * Fraction of wireframe lines drawn. At 1 it looks like CAD; lower reads as pencil scribble.
     */
    cageDensity?: number | null;
    /**
     * Same, on screens below 640px
     */
    cageDensityMobile?: number | null;
    cageOpacity?: number | null;
    /**
     * Changes which lines are drawn. Same number = same cage every load.
     */
    cageSeed?: number | null;
  };
  /**
   * The graphite-to-hot ramp, and the dark mass that makes red readable
   */
  ignitionColor?: {
    /**
     * Unlit cage — matches the pencil in the sketch video
     */
    coldColor?: string | null;
    warmColor?: string | null;
    hotColor?: string | null;
    /**
     * The very peak of the charge. Kept small and brief.
     */
    crestColor?: string | null;
    /**
     * Faint dark fill shown only during the transition. Without it the red washes out against the paper background.
     */
    darkMassOpacity?: number | null;
    glowDecay?: number | null;
  };
  /**
   * The cage appears over the still-drawing sketch video as a sphere, blooms outward into a polygon, then collapses into the logo shape.
   */
  ignitionOverlay?: {
    /**
     * Turning this off starts the transition at the video cut instead, with no sphere beforehand.
     */
    overlayEnabled?: boolean | null;
    /**
     * How long before the video ends the sphere appears
     */
    overlayLeadMs?: number | null;
    /**
     * Starting sphere size, as a multiple of the logo
     */
    sphereScale?: number | null;
    /**
     * The cage's TOTAL size when fully bloomed, as a multiple of the logo — measured corner to corner. Both this and the sphere are measured against the logo, so this number IS the final size rather than a multiplier on the sphere. Anything below the sphere size is raised to it.
     */
    bloomScale?: number | null;
    /**
     * Shape it blooms into. 8 is an octagon, 6 a hexagon.
     */
    polySides?: number | null;
    bloomStart?: number | null;
    bloomEnd?: number | null;
    /**
     * When the bloomed shape starts collapsing into the logo
     */
    morphStart?: number | null;
  };
  /**
   * Re-ignites while a visitor holds the logo and its skin peels away
   */
  ignitionPulse?: {
    pulseEnabled?: boolean | null;
    /**
     * Length of one pulse, and the gap before the next
     */
    pulseMs?: number | null;
  };
  /**
   * How much the cage writhes, and how it crackles
   */
  ignitionLife?: {
    /**
     * How far the wires drift, as a fraction of the logo radius
     */
    wireJitter?: number | null;
    wireSpeed?: number | null;
    /**
     * Randomness in the charge front. 0 gives a clean, even ring.
     */
    sparkStagger?: number | null;
    sparkRate?: number | null;
    /**
     * How many wires are lit at once. High values wash out.
     */
    sparkDensity?: number | null;
    /**
     * Sparking while the cage is still cold, over the video
     */
    sparkIdle?: number | null;
  };
  /**
   * Glowing particles at the cage junctions
   */
  ignitionEmbers?: {
    emberEnabled?: boolean | null;
    /**
     * Fraction of cage junctions that carry an ember
     */
    emberDensity?: number | null;
    emberSize?: number | null;
    emberTwinkle?: number | null;
    emberOpacity?: number | null;
  };
  /**
   * Coloured spheres orbiting the logo, each carrying one of the hero words. Turning this off removes them entirely — the hero keeps the logo, the video and the headline.
   */
  satellitesEnabled?: boolean | null;
  /**
   * Where the belt sits relative to the mark
   */
  satelliteField?: {
    /**
     * Orbit floor, as a multiple of the logo’s on-screen half-height
     */
    innerRadius?: number | null;
    /**
     * Reference radius, as a fraction of half the viewport’s smaller side. Satellites orbit inside a band of this — see “band inner/outer” below.
     */
    outerRadius?: number | null;
    mobileInnerRadius?: number | null;
    /**
     * Used below 640px. The desktop value leaves only about half the belt on a portrait screen.
     */
    mobileOuterRadius?: number | null;
    /**
     * Inclination in degrees. 0 is edge-on, 90 is face-on.
     */
    tilt?: number | null;
    tiltSideway?: number | null;
    /**
     * Lower is a stronger perspective
     */
    perspective?: number | null;
  };
  satelliteMotion?: {
    orbitSpeed?: number | null;
    /**
     * Counter-clockwise on screen. Off runs them clockwise.
     */
    orbitCcw?: boolean | null;
    speedScale?: number | null;
    /**
     * 0 leaves no trail, 50 is the longest streak
     */
    trail?: number | null;
  };
  satelliteLook?: {
    size?: number | null;
    alpha?: number | null;
    /**
     * 0 is a flat disc, 1 is a fully modelled sphere
     */
    shade?: number | null;
    /**
     * Extra near/far size difference beyond the perspective divide
     */
    depthScale?: number | null;
    streak?: number | null;
    /**
     * Outline radius as a multiple of the sphere. 0 removes it.
     */
    ring?: number | null;
    /**
     * Innermost satellite orbit, as a fraction of the outer radius
     */
    bandInner?: number | null;
    bandOuter?: number | null;
    /**
     * Per-satellite inclination variation, in degrees. 0 is one shared plane.
     */
    tiltSpread?: number | null;
    /**
     * Used for any satellite the colour list below does not cover
     */
    baseColor?: string | null;
  };
  /**
   * Colour belongs to the ORBIT SLOT, not to the word: the first row colours the first satellite regardless of which word it carries, and regardless of language. Reordering the hero words does NOT reorder these. Extra rows are ignored; satellites past the last row use the base colour above.
   */
  satelliteColors?:
    | {
        color: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The words themselves are the hero block’s “floating words” on the Home page, and the number of satellites follows that list.
   */
  satelliteLabels?: {
    mode?: ('always' | 'hover' | 'none') | null;
    size?: number | null;
    color?: string | null;
    offset?: number | null;
    hoverRadius?: number | null;
  };
  /**
   * What the satellites do while a visitor holds the logo. Shares the same gesture as the hold-to-separate effect above.
   */
  satelliteHold?: {
    /**
     * Stop orbiting and tremble in place while the logo is held
     */
    freeze?: boolean | null;
    shakePx?: number | null;
    shakeSpeed?: number | null;
  };
  satelliteBehaviour?: {
    entranceMs?: number | null;
    /**
     * Screens of scrolling over which the field dissolves. 0 never fades.
     */
    scrollFadeVh?: number | null;
    /**
     * Changing this reshuffles the starting arrangement
     */
    seed?: number | null;
  };
  /**
   * A single brass mascot orbiting the logo alongside the satellites, trailing gold dust and carrying its own word. Turning this off removes it entirely — nothing else in the hero changes.
   */
  mascotEnabled?: boolean | null;
  /**
   * The mascot’s word. NOT one of the hero “floating words” — those are localized and their count drives the satellites; this is the mascot’s own fixed name, shown identically in both languages.
   */
  mascotLabelText?: string | null;
  /**
   * The mascot shares the satellites’ orbital plane (tilt, roll, direction). These are its own place within it.
   */
  mascotOrbit?: {
    /**
     * As a fraction of the satellites’ outer radius. The bead band is 0.5–0.8.
     */
    radius?: number | null;
    mobileRadius?: number | null;
    /**
     * How far the mascot rides above the belt plane, in px. Keep this well clear of 0 — it is what keeps the mascot reading as nearer than the beads it passes.
     */
    height?: number | null;
    tiltOffset?: number | null;
    /**
     * Starting angle on the orbit, degrees
     */
    phase?: number | null;
    /**
     * Orbit speed as a multiple of the satellites’ orbit speed
     */
    speedScale?: number | null;
  };
  mascotLook?: {
    /**
     * On-screen diameter in px at zero depth
     */
    size?: number | null;
    mobileSize?: number | null;
    /**
     * Extra near/far size difference beyond the perspective divide. NOT the satellites’ 0.9 — that value is tuned for 4px beads.
     */
    depthScale?: number | null;
    opacity?: number | null;
    /**
     * Reflection strength. Brass is fully metallic — at 0 it goes black.
     */
    envIntensity?: number | null;
    lightIntensity?: number | null;
  };
  mascotSpin?: {
    /**
     * Degrees per second, independent of the orbit
     */
    spinSpeed?: number | null;
    spinTilt?: number | null;
    /**
     * Slow vertical float on top of the orbit
     */
    bobPx?: number | null;
    bobSeconds?: number | null;
  };
  /**
   * A shed particle field. Additive blending is a deliberate choice — the dust colour is picked bright to suit it.
   */
  mascotTrail?: {
    enabled?: boolean | null;
    /**
     * How long each mote lives
     */
    seconds?: number | null;
    /**
     * Motes per second
     */
    density?: number | null;
    /**
     * Mote diameter in px
     */
    size?: number | null;
    /**
     * Random scatter at emission, px
     */
    spread?: number | null;
    /**
     * How fast motes drift off the path, px/sec
     */
    drift?: number | null;
    /**
     * Hot-core strength
     */
    glow?: number | null;
    twinkle?: number | null;
    opacity?: number | null;
    /**
     * Additive blending. Off is slightly more saturated on the paper.
     */
    additive?: boolean | null;
    /**
     * The saturated body of each mote
     */
    color?: string | null;
    /**
     * The bright centre of each mote
     */
    coreColor?: string | null;
  };
  /**
   * The word’s text is set above (“mascot label text”). These control how it looks.
   */
  mascotLabel?: {
    enabled?: boolean | null;
    size?: number | null;
    color?: string | null;
    /**
     * Gap from the mascot’s edge, px
     */
    offset?: number | null;
    /**
     * Paper-coloured halo behind the word, px. Fixes the word going illegible where it crosses the mark’s red stroke. 0 is off.
     */
    halo?: number | null;
  };
  /**
   * Shares the same gesture as the hold-to-separate effect. Freeze + tremble in place while the logo is held.
   */
  mascotHold?: {
    freeze?: boolean | null;
    shakePx?: number | null;
    shakeSpeed?: number | null;
  };
  mascotBehaviour?: {
    entranceMs?: number | null;
    /**
     * Screens of scrolling over which the mascot dissolves. 0 never fades.
     */
    scrollFadeVh?: number | null;
  };
  /**
   * The mascot’s animated LED face. Turning this off restores its original painted eyes exactly — no socket darkening, no display. The expression shapes are not editable here: they were tuned on screen and are frozen in code, so changing one is a code change.
   */
  mascotEyesEnabled?: boolean | null;
  mascotEyesLook?: {
    /**
     * The lit eye. Amber rather than the reference’s cyan, so the hero keeps one warm accent instead of gaining a second, cold one.
     */
    color?: string | null;
    /**
     * Hot centre of the eye.
     */
    coreColor?: string | null;
    /**
     * Darkening over the faceplate. It exists to cover the mascot’s own PAINTED amber ovals — lighten it and the old eyes show through around the new ones.
     */
    socketColor?: string | null;
    glow?: number | null;
    /**
     * Half-distance between the two eyes.
     */
    gap?: number | null;
    /**
     * How far the darkening reaches. ⚠️ Anything drawn past this is CUT with a hard edge, not faded, and at 1.34 there is no headroom left — one expression already reaches 1.35. Raise this, never lower it.
     */
    socketSpan?: number | null;
  };
  mascotEyesScanlines?: {
    max?: number | null;
    /**
     * Body size below which scanlines are off. Deliberately above the mascot’s 28px base, so they appear only as it swings near — 7 lines over an 18px eye is moire, not texture.
     */
    minBodyPx?: number | null;
    ramp?: number | null;
  };
  /**
   * The mascot plays ONE expression each time its face sweeps past the viewer, then returns to neutral. There is no idle timer and no cursor tracking — the face is only toward you about a quarter of each turn.
   */
  mascotEyesBeat?: {
    glanceSeconds?: number | null;
    /**
     * Where in the glance the expression peaks.
     */
    glancePeak?: number | null;
    /**
     * How square-on the face must be to count as facing you.
     */
    facingThreshold?: number | null;
    /**
     * While the mark is held: the eyes widen, then squeeze shut past this point.
     */
    chargeCrossover?: number | null;
    noRepeat?: boolean | null;
  };
  /**
   * How often each expression is picked. 0 removes it entirely. “Neutral” is the resting face and “wide” belongs to the press-and-hold reaction, so both are 0 here by design.
   */
  mascotEyesWeights?: {
    neutral?: number | null;
    blink?: number | null;
    squint?: number | null;
    wide?: number | null;
    happy?: number | null;
    lookLeft?: number | null;
    lookRight?: number | null;
    lookUp?: number | null;
    lookDown?: number | null;
    lookUpLeft?: number | null;
    lookUpRight?: number | null;
    lookDownLeft?: number | null;
    lookDownRight?: number | null;
    wink?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "samsara-sequence".
 */
export interface SamsaraSequence {
  id: number;
  /**
   * Turning this OFF removes the whole transition from the page — no scroll listeners, no pin, no room. The hero keeps its orbiting mascot exactly as it was before Section 2 existed.
   */
  sequenceEnabled?: boolean | null;
  /**
   * One trackpad flick must stay ONE beat. Test any change with a flick, not a mouse wheel.
   */
  gestures?: {
    /**
     * Scroll gestures before SAMSARA leaves the hero. The last one commits, so 3 means two charge beats then the launch.
     */
    beatsToCommit?: number | null;
    /**
     * Wheel distance per beat. 230 is about two mouse notches, so roughly six notches to enter. Raise it if entry feels too easy; this is the first number to revisit if it feels heavy on a mouse.
     */
    wheelThreshold?: number | null;
    /**
     * Ignore further scrolling for this long after a beat lands.
     */
    cooldownMs?: number | null;
    /**
     * Stillness that ends a gesture. This is what keeps one long trackpad flick from counting as several beats.
     */
    quietMs?: number | null;
    /**
     * Finger travel in px per beat on touch.
     */
    touchThreshold?: number | null;
  };
  /**
   * Beat 1 must be unmistakable. A page that does not visibly respond to the first scroll reads as broken.
   */
  freeze?: {
    /**
     * Shake amplitude in px, one row per beat. Rows past the beat count are unused; deleting rows falls back to the built-in values.
     */
    shakePxPerBeat?:
      | {
          value: number;
          id?: string | null;
        }[]
      | null;
    /**
     * Shake frequency.
     */
    shakeHz?: number | null;
    /**
     * How far the logo has pulled apart at each beat, 0–1. The commit takes it to 1 regardless, so the last row only matters if the beat count is raised.
     */
    chargePerBeat?:
      | {
          value: number;
          id?: string | null;
        }[]
      | null;
  };
  transit?: {
    /**
     * The sweep from wherever SAMSARA was to the far point of the orbit, before the camera hands over.
     */
    halfOrbitMs?: number | null;
    /**
     * The drop from the back of the room to the first contact.
     */
    fallMs?: number | null;
    /**
     * 0 lands it dead, with no bounce at all.
     */
    bounceCount?: number | null;
    /**
     * Energy kept per bounce. Apex heights go h, then this fraction of h, then that fraction again.
     */
    restitution?: number | null;
    /**
     * One duration per bounce, shortening. Rows past the bounce count are unused.
     */
    bounceMs?:
      | {
          value: number;
          id?: string | null;
        }[]
      | null;
    /**
     * The rise from the last contact into the resting hover.
     */
    settleMs?: number | null;
  };
  /**
   * Fractions of the viewport, so the composition holds at every size. Desktop and portrait are set separately because SAMSARA sits beside Section 2’s content on wide screens and above it in portrait.
   */
  landing?: {
    /**
     * Landed height as a fraction of viewport height, desktop.
     */
    sizeFrac?: number | null;
    /**
     * The same, portrait (under 640px wide).
     */
    mobileSizeFrac?: number | null;
    /**
     * Landed centre across the viewport, desktop. 0.75 is right of centre.
     */
    xFrac?: number | null;
    /**
     * Landed centre down the viewport, desktop.
     */
    yFrac?: number | null;
    /**
     * Portrait: centred, sitting high in the frame.
     */
    mobileXFrac?: number | null;
    /**
     * Portrait height. Lowering this pushes SAMSARA down into whatever Section 2 renders below it.
     */
    mobileYFrac?: number | null;
    /**
     * Idle float once landed. 0 parks it perfectly still.
     */
    hoverBobPx?: number | null;
    /**
     * One full bob, up and back.
     */
    hoverBobMs?: number | null;
    /**
     * Where the face points once landed — pitch. 0/0/0 is frontal and level. Drag SAMSARA directly at /dev/samsara to find an angle, rather than guessing here.
     */
    rotXDeg?: number | null;
    /**
     * Yaw. This is the one that turns the face toward or away from the visitor.
     */
    rotYDeg?: number | null;
    /**
     * Roll — the head tilt.
     */
    rotZDeg?: number | null;
  };
  /**
   * Graphite on black: the Atelier drawing language inverted. The Section 2 block reads the background colour from here too, so the DOM behind the 3D layer always matches.
   */
  room?: {
    /**
     * Behind everything, and the page background of Section 2.
     */
    bgColor?: string | null;
    floorColor?: string | null;
    wallColor?: string | null;
    /**
     * The single shadow-casting light.
     */
    keyLightColor?: string | null;
    keyLightIntensity?: number | null;
    /**
     * Fill light. Too much and the room stops reading as dark.
     */
    ambientIntensity?: number | null;
    /**
     * Depth falloff on the room geometry. The scene is SHARED with the hero orbit, so this is not scene fog — it would tint the mascot while it is still circling the mark.
     */
    fogDensity?: number | null;
    /**
     * Changing this moves the camera to keep the landed size identical, so it changes how deep the room LOOKS rather than how big SAMSARA is.
     */
    cameraFovDeg?: number | null;
    /**
     * The room’s world-unit SCALE, not its apparent size. The camera is solved from it, so changing this pulls the camera back by the same factor and the picture does not change. To push the floor and walls out of shot, use Surface extent below.
     */
    depth?: number | null;
    /**
     * How far the floor and walls run past the frame. 1 ends them exactly at the frame edge, which is where their edges are visible. Raise it until the side walls and the wall tops leave shot and the space reads as unbounded — the key light does not reach further, so the surfaces fall off into darkness on their own. The floor stays put at any value, so SAMSARA’s bounce keeps its contact shadow.
     */
    extent?: number | null;
    /**
     * Warm bronze-brass. Inert while the strength below is 0.
     */
    mascotTintColor?: string | null;
    /**
     * How much of the tint colour is mixed into the body in the room.
     */
    mascotTintStrength?: number | null;
    /**
     * Pushes the metal from polished toward matte. Independent of the tint — they were coupled once, and turning the tint off silently killed this as well.
     */
    mascotRoughnessBoost?: number | null;
    /**
     * What the metal REFLECTS. On a fully metallic surface this does most of the colouring, far more than the lights do.
     */
    envColor?: string | null;
    envIntensity?: number | null;
  };
  /**
   * Only while landed. The hero orbit is never draggable.
   */
  drag?: {
    enabled?: boolean | null;
    sensitivityDegPerPx?: number | null;
    /**
     * How far up and down it can be turned before it stops.
     */
    maxPitchDeg?: number | null;
    /**
     * Spin kept per second after release. Lower stops it sooner.
     */
    damping?: number | null;
    /**
     * Stillness before it springs back to the parked orientation.
     */
    returnDelayMs?: number | null;
    /**
     * How long that return takes.
     */
    returnMs?: number | null;
  };
  /**
   * The room shows SAMSARA still and close, so this is a slow resting face rather than the hero orbit’s glance beat.
   */
  idleEyes?: {
    /**
     * Between expression changes.
     */
    intervalMs?: number | null;
    /**
     * The little shake when a visitor presses and holds. 0 turns it off.
     */
    smileShakePx?: number | null;
    smileShakeMs?: number | null;
    /**
     * What the face does while a visitor presses and holds it.
     */
    holdExpression?:
      | (
          | 'neutral'
          | 'blink'
          | 'squint'
          | 'happy'
          | 'wide'
          | 'wink'
          | 'lookLeft'
          | 'lookRight'
          | 'lookUp'
          | 'lookDown'
          | 'lookUpLeft'
          | 'lookUpRight'
          | 'lookDownLeft'
          | 'lookDownRight'
        )
      | null;
    /**
     * How often each is picked in the room. 0 removes it. The owner settled on a calm resting face — mostly neutral, an occasional blink — so most of these are 0 by design, not by oversight.
     */
    weights?: {
      neutral?: number | null;
      blink?: number | null;
      squint?: number | null;
      happy?: number | null;
      wide?: number | null;
      wink?: number | null;
      lookLeft?: number | null;
      lookRight?: number | null;
      lookUp?: number | null;
      lookDown?: number | null;
      lookUpLeft?: number | null;
      lookUpRight?: number | null;
      lookDownLeft?: number | null;
      lookDownRight?: number | null;
    };
  };
  /**
   * Puffs of golden smoke shed from BEHIND SAMSARA once it has parked, on a timer. Distances are in body radii, not pixels, so it holds its scale relative to SAMSARA on every screen. Smoke reads as smoke because the puffs are FEW, LARGE, FAINT and EXPANDING — raising the count or the opacity turns it back into dust.
   */
  burst?: {
    enabled?: boolean | null;
    /**
     * Between bursts. The first one waits a full interval after landing, so it does not arrive under the bounce and the settle.
     */
    intervalMs?: number | null;
    /**
     * Motes per burst. 0 is another way to turn it off.
     */
    count?: number | null;
    /**
     * How long a mote lasts, before a per-mote spread of 0.7-1.3x.
     */
    seconds?: number | null;
    /**
     * Outward speed, in body radii per second.
     */
    speed?: number | null;
    /**
     * How much each puff expands over its life. Above 1 it billows out as it fades, which is the strongest smoke cue; 1 holds a flat disc and below 1 it shrinks to a grain and reads as dust.
     */
    growth?: number | null;
    /**
     * Lateral curl. Each puff drifts on its own slow wander, so the cloud folds instead of expanding as a clean ball. 0 makes it a tidy sphere.
     */
    swirl?: number | null;
    /**
     * How quickly motes slow down. 0 lets them fly on at full speed and leave the frame.
     */
    drag?: number | null;
    /**
     * Upward drift. Negative makes the dust fall instead.
     */
    rise?: number | null;
    /**
     * How far past the surface motes are born.
     */
    spread?: number | null;
    /**
     * How far BEHIND the body the burst starts. Larger hides the moment of birth better; 0 lets motes appear level with the silhouette.
     */
    backOffset?: number | null;
    /**
     * Puff size in px at birth, measured at SAMSARA’s own depth. Large is correct here — these overlap to make the volume.
     */
    size?: number | null;
    opacity?: number | null;
    /**
     * How much of each puff is hot centre rather than body colour. Keep it low: a bright middle puts a visible grain back inside every puff.
     */
    glow?: number | null;
    /**
     * The hero’s own gold, so the room reads as the same material.
     */
    color?: string | null;
    /**
     * The warmer centre of each puff.
     */
    coreColor?: string | null;
  };
  /**
   * Two instances of ONE model, sharing one download. They differ by DEPTH, not by size, which is why there is a single size control and four positions.
   */
  emitters?: {
    /**
     * On-screen height as a fraction of viewport height — the same units as SAMSARA’s own landing size. Both orbs share it.
     */
    sizeFrac?: number | null;
    /**
     * Portrait, where the orbs flank the screen below SAMSARA.
     */
    mobileSizeFrac?: number | null;
    near?: {
      xFrac?: number | null;
      yFrac?: number | null;
      /**
       * 0 = at the camera, 1 = at the back wall. This is what makes the two orbs look like different sizes — they are one model at two depths, not two sizes.
       */
      depthFrac?: number | null;
    };
    far?: {
      xFrac?: number | null;
      yFrac?: number | null;
      /**
       * 0 = at the camera, 1 = at the back wall. This is what makes the two orbs look like different sizes — they are one model at two depths, not two sizes.
       */
      depthFrac?: number | null;
    };
    mobileNear?: {
      xFrac?: number | null;
      yFrac?: number | null;
      /**
       * 0 = at the camera, 1 = at the back wall. This is what makes the two orbs look like different sizes — they are one model at two depths, not two sizes.
       */
      depthFrac?: number | null;
    };
    mobileFar?: {
      xFrac?: number | null;
      yFrac?: number | null;
      /**
       * 0 = at the camera, 1 = at the back wall. This is what makes the two orbs look like different sizes — they are one model at two depths, not two sizes.
       */
      depthFrac?: number | null;
    };
    /**
     * The four steam nozzles, in orb radii. ONE set of coordinates, mirrored on X and Z — the nozzles sit in a square on the underside, so four loose values could only drift out of it. Turn on the port markers below to place them by eye.
     */
    portX?: number | null;
    /**
     * Height. Negative, since the nozzles are underneath.
     */
    portY?: number | null;
    portZ?: number | null;
    lensX?: number | null;
    /**
     * The domed projector lens on top. The light shafts start here.
     */
    lensY?: number | null;
    lensZ?: number | null;
    /**
     * TUNING AID — leave off for visitors. Draws a green marker at each nozzle and a pink one at the lens. Without it a port is invisible until smoke happens to come out of it, which is a slow way to find out where it actually is.
     */
    showPorts?: boolean | null;
    /**
     * Pitch, yaw and roll in degrees. The four afterburners and the projector lens are part of the body, so they turn with it — the smoke follows.
     */
    nearRot?: {
      xDeg?: number | null;
      yDeg?: number | null;
      zDeg?: number | null;
    };
    /**
     * Pitch, yaw and roll in degrees. The four afterburners and the projector lens are part of the body, so they turn with it — the smoke follows.
     */
    farRot?: {
      xDeg?: number | null;
      yDeg?: number | null;
      zDeg?: number | null;
    };
    /**
     * How long one orb takes to fly in from behind the camera.
     */
    entryMs?: number | null;
    /**
     * How far the far orb lags the near one. At 0 they arrive together and read as one rigid object rather than two machines.
     */
    entryStaggerMs?: number | null;
    /**
     * Idle float, in orb radii. The two orbs bob out of phase deliberately.
     */
    bobAmp?: number | null;
    bobMs?: number | null;
    /**
     * Puffs per second PER PORT, across the four afterburners. CONTINUOUS — the orbs emit from the moment they appear until the room closes.
     */
    thrustRate?: number | null;
    thrustSpread?: number | null;
    /**
     * How far each plume leans away from the orb’s axis, as a multiple of that nozzle’s own offset. At 0 all four jets are parallel and read as one flame rather than four afterburners.
     */
    plumeOut?: number | null;
    /**
     * How hard the plume is driven along the orb’s own Y, in radii per second. Negative vents out of the underside.
     */
    plumeY?: number | null;
    /**
     * In orb radii, so it holds its proportion at every viewport.
     */
    puffSize?: number | null;
    /**
     * How long a puff lasts. Lifetimes vary up to 1.25x around this, so no two are identical. Longer means a denser trail, since the emission is continuous.
     */
    puffLifeMs?: number | null;
    /**
     * Warm grey steam — deliberately not the gold of SAMSARA’s own bursts.
     */
    puffColor?: string | null;
    puffOpacity?: number | null;
  };
  /**
   * The two brass tubes on SAMSARA’s upper rear. One port is configured and MIRRORED across the centreline, because the tubes are symmetric on the model — a second set of coordinates could only drift out of line with them. The plume turns with the body, so parking or dragging SAMSARA carries it along.
   */
  exhaust?: {
    /**
     * Off leaves SAMSARA’s own golden burst untouched — they are separate systems.
     */
    enabled?: boolean | null;
    /**
     * Right-hand tube, in body radii from the centre. Mirrored to the left.
     */
    portX?: number | null;
    /**
     * Height. The tubes sit high on the hull.
     */
    portY?: number | null;
    /**
     * Depth. NEGATIVE is behind — the face is +Z, so a positive value puts smoke on SAMSARA’s face.
     */
    portZ?: number | null;
    /**
     * Outward lean of the plume. Mirrors with the port.
     */
    dirX?: number | null;
    /**
     * Rise. Keep positive, or the plume pools under a hovering body.
     */
    dirY?: number | null;
    /**
     * Backward push, away from the face.
     */
    dirZ?: number | null;
    /**
     * Puffs per second PER TUBE. Continuous, not a repeating burst — an engine idles.
     */
    rate?: number | null;
    spread?: number | null;
    /**
     * Pixels at the body’s depth, the same units as the golden burst’s size.
     */
    puffSize?: number | null;
    puffLifeMs?: number | null;
    /**
     * Warm grey steam, matching the orbs rather than the golden burst.
     */
    puffColor?: string | null;
    puffOpacity?: number | null;
  };
  /**
   * The screen the two orbs project. It will later carry subtitles and option buttons as real DOM on top, which is why the flicker below applies to the GLASS ONLY — flickering text would defeat the accessibility feature it exists to provide.
   */
  hologram?: {
    wFrac?: number | null;
    /**
     * The artwork’s width over its height. The panel’s height follows from this and its width, so the drawing never stretches — it must MATCH public/hud/panel.png, and scripts/build-hud-sdf.mjs prints the source aspect on every run.
     */
    panelAspect?: number | null;
    /**
     * Landscape. Keep the screen clear of SAMSARA, which parks at 0.75.
     */
    xFrac?: number | null;
    yFrac?: number | null;
    mobileWFrac?: number | null;
    mobileXFrac?: number | null;
    /**
     * Portrait. The screen goes BELOW SAMSARA, which parks at 0.3.
     */
    mobileYFrac?: number | null;
    /**
     * The screen flickers first and then resolves — an unstable ramp, not a clean fade.
     */
    formMs?: number | null;
    /**
     * The permanent flicker interval once the screen is live.
     */
    flickerMs?: number | null;
    /**
     * Keep well below the interval, or the screen reads as broken rather than as a projection.
     */
    flickerDurMs?: number | null;
    /**
     * How far the glass dips. Never 1 — a screen that fully extinguishes reads as a fault rather than a hologram.
     */
    flickerDepth?: number | null;
    /**
     * The screen’s own amber.
     */
    glassColor?: string | null;
    glassOpacity?: number | null;
    /**
     * How far the panel’s own halo carries. The artwork is drawn flat with no glow baked in, so all of it comes from here — and that is what lets it breathe with the flicker.
     */
    glassGlow?: number | null;
    /**
     * The light shafts from each lens. Usually the same amber as the glass.
     */
    shaftColor?: string | null;
    /**
     * The shafts are additive geometry, not fog — fog is banned in this room because it shares its scene with the hero orbit and would tint SAMSARA mid-flight.
     */
    shaftOpacity?: number | null;
    /**
     * Brightness distribution INSIDE the fan — use shaftHalfDeg to set how wide it opens. An angular falloff, not a radius — the cone mesh this replaced on 2026-09-04 measured the same idea in orb radii, so a value from before that date does not carry over.
     */
    shaftSpread?: number | null;
    /**
     * Half-angle of the fan — where it actually ends. Not the same as shaft spread, which only shapes brightness inside it: a cosine falloff reaches zero at exactly 90 degrees whatever it is set to, so without this the fan always throws a tail out sideways.
     */
    shaftHalfDeg?: number | null;
    /**
     * TUNING AID — leave off for visitors. Draws the fan’s two edges in green so the half-angle is visible while it is being set.
     */
    shaftGuide?: boolean | null;
    /**
     * How far the rays travel, as a multiple of the frame’s diagonal at the orb’s own depth. At 1 or above the fan always runs off the frame; below 1 you will see where it ends.
     */
    shaftReach?: number | null;
    /**
     * Ray density. They are banded on the angle, so spacing is naturally wide near the fan’s axis and tight at its edges.
     */
    shaftRays?: number | null;
    /**
     * Shimmer speed. 0 freezes the fan.
     */
    shaftSpeed?: number | null;
    /**
     * Falloff shape along a ray, not a distance — the reach sets where a ray ends. 1 is a straight ramp; below 1 it stays bright most of the way.
     */
    shaftFade?: number | null;
    /**
     * How dark it gets between rays. At 1 the fan is a soft wash; raise it until the streaks separate.
     */
    shaftContrast?: number | null;
    /**
     * How strongly the screen’s own left and right edges hold the light in. 1 keeps the fan inside the panel; 0 lets it run across the room.
     */
    shaftBound?: number | null;
    /**
     * A hot bloom where the rays leave the lens.
     */
    shaftCore?: number | null;
    /**
     * How sharply each ray closes to a point. 1 leaves the natural wedge, which ends blunt because a wedge is widest at its far end.
     */
    shaftTip?: number | null;
    /**
     * The colour at the throat of the beam, before it cools to the shaft colour.
     */
    shaftCoreColor?: string | null;
    /**
     * How far the hot colour carries before the ray is fully amber.
     */
    shaftCoreSpan?: number | null;
    /**
     * Where this orb’s fan sits and which way it points, ON SCREEN. The nudge is in orb radii from the lens; the angle turns the fan anticlockwise from its aim at the screen’s centre, so 0 leaves it exactly where it was. Spread and reach multiply the global half-angle and reach for this fan alone — 1 leaves them be.
     */
    nearShaft?: {
      dx?: number | null;
      dy?: number | null;
      angleDeg?: number | null;
      spread?: number | null;
      reach?: number | null;
    };
    /**
     * Where this orb’s fan sits and which way it points, ON SCREEN. The nudge is in orb radii from the lens; the angle turns the fan anticlockwise from its aim at the screen’s centre, so 0 leaves it exactly where it was. Spread and reach multiply the global half-angle and reach for this fan alone — 1 leaves them be.
     */
    farShaft?: {
      dx?: number | null;
      dy?: number | null;
      angleDeg?: number | null;
      spread?: number | null;
      reach?: number | null;
    };
  };
  /**
   * Scrolling up from the room returns to the hero. A quick exit, deliberately NOT a rewind of the fall.
   */
  exitMs?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  email?: T;
  locationLine?: T;
  timezone?: T;
  socials?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  navLabels?:
    | T
    | {
        home?: T;
        manifesto?: T;
        archive?: T;
      };
  archiveCountTemplate?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-effects_select".
 */
export interface HeroEffectsSelect<T extends boolean = true> {
  separationEnabled?: T;
  timing?:
    | T
    | {
        chargeMs?: T;
        reformMs?: T;
        separateStart?: T;
        staggerMax?: T;
      };
  motion?:
    | T
    | {
        spreadFrac?: T;
        spreadVar?: T;
        lateralDrift?: T;
        spinMin?: T;
        spinMax?: T;
        capNormalMin?: T;
      };
  material?:
    | T
    | {
        normalFollow?: T;
        hatchStrength?: T;
        hatchScale?: T;
        shineStrength?: T;
        shineWidth?: T;
        shineSpeed?: T;
        shineChargeBoost?: T;
        shineWarm?: T;
        shineBright?: T;
      };
  body?:
    | T
    | {
        skinOpacity?: T;
        bodyOpacity?: T;
        bodyEdgeOpacity?: T;
        bodyEdgeAngle?: T;
      };
  feel?:
    | T
    | {
        vibrateFrac?: T;
        vibratePhaseStep?: T;
        dragThresholdPx?: T;
      };
  ignitionEnabled?: T;
  ignitionTiming?:
    | T
    | {
        ignitionMs?: T;
        seedEnd?: T;
        frontEnd?: T;
        cueFrac?: T;
      };
  ignitionShape?:
    | T
    | {
        seedOffsetX?: T;
        seedOffsetY?: T;
        seedOffsetZ?: T;
        frontSoftness?: T;
        wakeLag?: T;
        coreRadius?: T;
        coreStrength?: T;
      };
  ignitionCage?:
    | T
    | {
        cageDensity?: T;
        cageDensityMobile?: T;
        cageOpacity?: T;
        cageSeed?: T;
      };
  ignitionColor?:
    | T
    | {
        coldColor?: T;
        warmColor?: T;
        hotColor?: T;
        crestColor?: T;
        darkMassOpacity?: T;
        glowDecay?: T;
      };
  ignitionOverlay?:
    | T
    | {
        overlayEnabled?: T;
        overlayLeadMs?: T;
        sphereScale?: T;
        bloomScale?: T;
        polySides?: T;
        bloomStart?: T;
        bloomEnd?: T;
        morphStart?: T;
      };
  ignitionPulse?:
    | T
    | {
        pulseEnabled?: T;
        pulseMs?: T;
      };
  ignitionLife?:
    | T
    | {
        wireJitter?: T;
        wireSpeed?: T;
        sparkStagger?: T;
        sparkRate?: T;
        sparkDensity?: T;
        sparkIdle?: T;
      };
  ignitionEmbers?:
    | T
    | {
        emberEnabled?: T;
        emberDensity?: T;
        emberSize?: T;
        emberTwinkle?: T;
        emberOpacity?: T;
      };
  satellitesEnabled?: T;
  satelliteField?:
    | T
    | {
        innerRadius?: T;
        outerRadius?: T;
        mobileInnerRadius?: T;
        mobileOuterRadius?: T;
        tilt?: T;
        tiltSideway?: T;
        perspective?: T;
      };
  satelliteMotion?:
    | T
    | {
        orbitSpeed?: T;
        orbitCcw?: T;
        speedScale?: T;
        trail?: T;
      };
  satelliteLook?:
    | T
    | {
        size?: T;
        alpha?: T;
        shade?: T;
        depthScale?: T;
        streak?: T;
        ring?: T;
        bandInner?: T;
        bandOuter?: T;
        tiltSpread?: T;
        baseColor?: T;
      };
  satelliteColors?:
    | T
    | {
        color?: T;
        id?: T;
      };
  satelliteLabels?:
    | T
    | {
        mode?: T;
        size?: T;
        color?: T;
        offset?: T;
        hoverRadius?: T;
      };
  satelliteHold?:
    | T
    | {
        freeze?: T;
        shakePx?: T;
        shakeSpeed?: T;
      };
  satelliteBehaviour?:
    | T
    | {
        entranceMs?: T;
        scrollFadeVh?: T;
        seed?: T;
      };
  mascotEnabled?: T;
  mascotLabelText?: T;
  mascotOrbit?:
    | T
    | {
        radius?: T;
        mobileRadius?: T;
        height?: T;
        tiltOffset?: T;
        phase?: T;
        speedScale?: T;
      };
  mascotLook?:
    | T
    | {
        size?: T;
        mobileSize?: T;
        depthScale?: T;
        opacity?: T;
        envIntensity?: T;
        lightIntensity?: T;
      };
  mascotSpin?:
    | T
    | {
        spinSpeed?: T;
        spinTilt?: T;
        bobPx?: T;
        bobSeconds?: T;
      };
  mascotTrail?:
    | T
    | {
        enabled?: T;
        seconds?: T;
        density?: T;
        size?: T;
        spread?: T;
        drift?: T;
        glow?: T;
        twinkle?: T;
        opacity?: T;
        additive?: T;
        color?: T;
        coreColor?: T;
      };
  mascotLabel?:
    | T
    | {
        enabled?: T;
        size?: T;
        color?: T;
        offset?: T;
        halo?: T;
      };
  mascotHold?:
    | T
    | {
        freeze?: T;
        shakePx?: T;
        shakeSpeed?: T;
      };
  mascotBehaviour?:
    | T
    | {
        entranceMs?: T;
        scrollFadeVh?: T;
      };
  mascotEyesEnabled?: T;
  mascotEyesLook?:
    | T
    | {
        color?: T;
        coreColor?: T;
        socketColor?: T;
        glow?: T;
        gap?: T;
        socketSpan?: T;
      };
  mascotEyesScanlines?:
    | T
    | {
        max?: T;
        minBodyPx?: T;
        ramp?: T;
      };
  mascotEyesBeat?:
    | T
    | {
        glanceSeconds?: T;
        glancePeak?: T;
        facingThreshold?: T;
        chargeCrossover?: T;
        noRepeat?: T;
      };
  mascotEyesWeights?:
    | T
    | {
        neutral?: T;
        blink?: T;
        squint?: T;
        wide?: T;
        happy?: T;
        lookLeft?: T;
        lookRight?: T;
        lookUp?: T;
        lookDown?: T;
        lookUpLeft?: T;
        lookUpRight?: T;
        lookDownLeft?: T;
        lookDownRight?: T;
        wink?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "samsara-sequence_select".
 */
export interface SamsaraSequenceSelect<T extends boolean = true> {
  sequenceEnabled?: T;
  gestures?:
    | T
    | {
        beatsToCommit?: T;
        wheelThreshold?: T;
        cooldownMs?: T;
        quietMs?: T;
        touchThreshold?: T;
      };
  freeze?:
    | T
    | {
        shakePxPerBeat?:
          | T
          | {
              value?: T;
              id?: T;
            };
        shakeHz?: T;
        chargePerBeat?:
          | T
          | {
              value?: T;
              id?: T;
            };
      };
  transit?:
    | T
    | {
        halfOrbitMs?: T;
        fallMs?: T;
        bounceCount?: T;
        restitution?: T;
        bounceMs?:
          | T
          | {
              value?: T;
              id?: T;
            };
        settleMs?: T;
      };
  landing?:
    | T
    | {
        sizeFrac?: T;
        mobileSizeFrac?: T;
        xFrac?: T;
        yFrac?: T;
        mobileXFrac?: T;
        mobileYFrac?: T;
        hoverBobPx?: T;
        hoverBobMs?: T;
        rotXDeg?: T;
        rotYDeg?: T;
        rotZDeg?: T;
      };
  room?:
    | T
    | {
        bgColor?: T;
        floorColor?: T;
        wallColor?: T;
        keyLightColor?: T;
        keyLightIntensity?: T;
        ambientIntensity?: T;
        fogDensity?: T;
        cameraFovDeg?: T;
        depth?: T;
        extent?: T;
        mascotTintColor?: T;
        mascotTintStrength?: T;
        mascotRoughnessBoost?: T;
        envColor?: T;
        envIntensity?: T;
      };
  drag?:
    | T
    | {
        enabled?: T;
        sensitivityDegPerPx?: T;
        maxPitchDeg?: T;
        damping?: T;
        returnDelayMs?: T;
        returnMs?: T;
      };
  idleEyes?:
    | T
    | {
        intervalMs?: T;
        smileShakePx?: T;
        smileShakeMs?: T;
        holdExpression?: T;
        weights?:
          | T
          | {
              neutral?: T;
              blink?: T;
              squint?: T;
              happy?: T;
              wide?: T;
              wink?: T;
              lookLeft?: T;
              lookRight?: T;
              lookUp?: T;
              lookDown?: T;
              lookUpLeft?: T;
              lookUpRight?: T;
              lookDownLeft?: T;
              lookDownRight?: T;
            };
      };
  burst?:
    | T
    | {
        enabled?: T;
        intervalMs?: T;
        count?: T;
        seconds?: T;
        speed?: T;
        growth?: T;
        swirl?: T;
        drag?: T;
        rise?: T;
        spread?: T;
        backOffset?: T;
        size?: T;
        opacity?: T;
        glow?: T;
        color?: T;
        coreColor?: T;
      };
  emitters?:
    | T
    | {
        sizeFrac?: T;
        mobileSizeFrac?: T;
        near?:
          | T
          | {
              xFrac?: T;
              yFrac?: T;
              depthFrac?: T;
            };
        far?:
          | T
          | {
              xFrac?: T;
              yFrac?: T;
              depthFrac?: T;
            };
        mobileNear?:
          | T
          | {
              xFrac?: T;
              yFrac?: T;
              depthFrac?: T;
            };
        mobileFar?:
          | T
          | {
              xFrac?: T;
              yFrac?: T;
              depthFrac?: T;
            };
        portX?: T;
        portY?: T;
        portZ?: T;
        lensX?: T;
        lensY?: T;
        lensZ?: T;
        showPorts?: T;
        nearRot?:
          | T
          | {
              xDeg?: T;
              yDeg?: T;
              zDeg?: T;
            };
        farRot?:
          | T
          | {
              xDeg?: T;
              yDeg?: T;
              zDeg?: T;
            };
        entryMs?: T;
        entryStaggerMs?: T;
        bobAmp?: T;
        bobMs?: T;
        thrustRate?: T;
        thrustSpread?: T;
        plumeOut?: T;
        plumeY?: T;
        puffSize?: T;
        puffLifeMs?: T;
        puffColor?: T;
        puffOpacity?: T;
      };
  exhaust?:
    | T
    | {
        enabled?: T;
        portX?: T;
        portY?: T;
        portZ?: T;
        dirX?: T;
        dirY?: T;
        dirZ?: T;
        rate?: T;
        spread?: T;
        puffSize?: T;
        puffLifeMs?: T;
        puffColor?: T;
        puffOpacity?: T;
      };
  hologram?:
    | T
    | {
        wFrac?: T;
        panelAspect?: T;
        xFrac?: T;
        yFrac?: T;
        mobileWFrac?: T;
        mobileXFrac?: T;
        mobileYFrac?: T;
        formMs?: T;
        flickerMs?: T;
        flickerDurMs?: T;
        flickerDepth?: T;
        glassColor?: T;
        glassOpacity?: T;
        glassGlow?: T;
        shaftColor?: T;
        shaftOpacity?: T;
        shaftSpread?: T;
        shaftHalfDeg?: T;
        shaftGuide?: T;
        shaftReach?: T;
        shaftRays?: T;
        shaftSpeed?: T;
        shaftFade?: T;
        shaftContrast?: T;
        shaftBound?: T;
        shaftCore?: T;
        shaftTip?: T;
        shaftCoreColor?: T;
        shaftCoreSpan?: T;
        nearShaft?:
          | T
          | {
              dx?: T;
              dy?: T;
              angleDeg?: T;
              spread?: T;
              reach?: T;
            };
        farShaft?:
          | T
          | {
              dx?: T;
              dy?: T;
              angleDeg?: T;
              spread?: T;
              reach?: T;
            };
      };
  exitMs?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}